# Chapter 3 : Maryland Automotive Industry - Detailed Segment Analysis

#### Total Cars Sold
Look at how new and used cars sold change over time and whether the changes in these proportions can explain the change in total cars sold.

### Import Packages

In [11]:
import pandas as pd # for data frames
import matplotlib.pyplot as plt # for plotting graphs

### Load Functions

### Load Data

In [13]:
# total cars sold
data = pd.read_csv('/Users/ben_nicholson/Visual_Code_Projects/Personal_Projects/Maryland Automotive Industry/preprocessed_datasets/combined_data/car_sales.csv')

#### Total Cars Sold Data
- Deseasonlised Cars Sold
- Deseasonlised New Cars Sold
- Deseasonlised Used Cars Sold

In [14]:
# load in total cars sold

#### Value Cars Sold Data

In [4]:
# load in economic data
economic_data = pd.read_csv('/Users/ben_nicholson/Visual_Code_Projects/Personal_Projects/Maryland Automotive Industry/preprocessed_datasets/combined_data/economic_data.csv')
economic_data.rename(columns={'Unnamed: 0':'date'},inplace=True)
economic_data

,date,yoy_inflation,interest_rate,fuel_price,consumer_confidence,unemployment_rate,gdp_growth
0,2002-01-01,NaN,1.73,0.634,NaN,5.0,NaN
1,2002-02-01,NaN,1.74,0.631,NaN,5.0,0.376418
2,2002-03-01,NaN,1.73,0.764,NaN,5.0,0.375007
3,2002-04-01,NaN,1.75,0.941,NaN,4.9,0.373606
4,2002-05-01,NaN,1.75,0.945,NaN,4.9,0.372215
...,...,...,...,...,...,...,...
259,2023-08-01,3.718721,5.33,NaN,97.94846,1.7,NaN
260,2023-09-01,3.694055,5.33,NaN,97.76891,1.6,NaN
261,2023-10-01,3.245787,5.33,NaN,97.56094,1.7,NaN
262,2023-11-01,3.139482,5.33,NaN,97.63428,1.8,NaN
263,2023-12-01,3.323160,5.33,NaN,98.15100,1.9,NaN

In [7]:
# load in relevant car sales data 
combined_data = pd.read_csv('/Users/ben_nicholson/Visual_Code_Projects/Personal_Projects/Maryland Automotive Industry/preprocessed_datasets/combined_data/complete_data.csv')

In [10]:
combined_data.corr()[combined_data.corr()>0.70]

,total_cars_sold,new_cars_sold,used_cars_sold,total_value_cars_sold,new_value_cars_sold,used_value_cars_sold,electric,plug-in_hybrid,total_electric_sales,real_value_cars_sold,...,real_used_value_cars_sold,real_average_price_cars_sold,real_new_average_price_cars_sold,real_used_average_price_cars_sold,yoy_inflation,interest_rate,fuel_price,consumer_confidence,unemployment_rate,gdp_growth
total_cars_sold,1.000000,0.870326,0.931142,NaN,NaN,NaN,NaN,NaN,NaN,0.819429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
new_cars_sold,0.870326,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.837672,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
used_cars_sold,0.931142,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
total_value_cars_sold,NaN,NaN,NaN,1.000000,0.948136,0.933918,NaN,NaN,NaN,0.714363,...,0.899740,NaN,0.700450,0.757046,NaN,NaN,NaN,NaN,NaN,NaN
new_value_cars_sold,NaN,NaN,NaN,0.948136,1.000000,0.771847,NaN,NaN,NaN,0.838221,...,0.823597,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
used_value_cars_sold,NaN,NaN,NaN,0.933918,0.771847,1.000000,NaN,NaN,NaN,NaN,...,0.873436,NaN,0.807160,0.846910,NaN,NaN,NaN,NaN,NaN,NaN
electric,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.991404,0.999438,NaN,...,NaN,NaN,0.771769,NaN,NaN,0.955899,0.947946,NaN,NaN,NaN
plug-in_hybrid,NaN,NaN,NaN,NaN,NaN,NaN,0.991404,1.000000,0.995234,NaN,...,NaN,NaN,0.822258,0.719391,NaN,0.928509,0.934268,NaN,NaN,NaN
total_electric_sales,NaN,NaN,NaN,NaN,NaN,NaN,0.999438,0.995234,1.000000,NaN,...,NaN,NaN,0.785976,NaN,NaN,0.950447,0.944067,NaN,NaN,NaN
real_value_cars_sold,0.819429,0.837672,NaN,0.714363,0.838221,NaN,NaN,NaN,NaN,1.000000,...,0.798725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
real_new_value_cars_sold,0.794956,0.942811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.939565,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
real_used_value_cars_sold,NaN,NaN,NaN,0.899740,0.823597,0.873436,NaN,NaN,NaN,0.798725,...,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
real_average_price_cars_sold,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.000000,NaN,0.743504,NaN,NaN,NaN,NaN,NaN,NaN
real_new_average_price_cars_sold,NaN,NaN,NaN,0.700450,NaN,0.807160,0.771769,0.822258,0.785976,NaN,...,NaN,NaN,1.000000,0.971707,NaN,NaN,NaN,NaN,NaN,NaN
real_used_average_price_cars_sold,NaN,NaN,NaN,0.757046,NaN,0.846910,NaN,0.719391,NaN,NaN,...,NaN,0.743504,0.971707,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
yoy_inflation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
interest_rate,NaN,NaN,NaN,NaN,NaN,NaN,0.955899,0.928509,0.950447,NaN,...,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN
fuel_price,NaN,NaN,NaN,NaN,NaN,NaN,0.947946,0.934268,0.944067,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN
consumer_confidence,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
unemployment_rate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
gdp_growth,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0